services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - watcher-network
  api:
    build: .
    container_name: api_watcher
    restart: always
    ports:
      - "8083:8083"
    networks:
      - watcher-network

volumes:
  mongo_data:
    driver: local

networks:
  watcher-network:
    driver: bridge

